[CM-885] - Added support to update TeamId in iOS
Kommunicate-io/Kommunicate-Flutter-Plugin pull request #59
Opened 2022-04-27 07:45 UTC by amntoppo

KommunicateFlutterPlugin.updateTeamId({
                      //'conversationId': 70780495,
                      'clientConversationId': '69360869',
                      'teamId': '63641656'
                    })
We can pass either conversationID (integer) or clientConversationID (string) in the object.

2022-05-02 05:31 UTC, Sathyan-Elangovan requested changes

2022-05-02 05:31 UTC, Sathyan-Elangovan commented on android/src/main/java/io/kommunicate/kommunicate_flutter_plugin/KmMethodHandler.java
> +                            (String) call.argument("teamId"),
What if both conversationId & clientConversation null?what will happen?Can we add check for it? what about login check ?

2022-05-02 05:31 UTC, Sathyan-Elangovan commented on example/lib/home.dart
> +                      'clientConversationId': '69360869',
Why hardcoding client conversationId & teamId here? Also remove that commented code as well

2022-05-02 05:31 UTC, Sathyan-Elangovan commented on ios/Classes/SwiftKommunicateFlutterPlugin.swift
> +                                    alChannelService.getChannelInformation(NSNumber(value: conversationId!), orClientChannelKey: nil) { (channel) in
Avoid force unwrapping it. `conversationId! ` will crash if conversation is nil

2022-05-02 05:31 UTC, Sathyan-Elangovan commented on ios/Classes/SwiftKommunicateFlutterPlugin.swift
> +                            return
we need trigger error callback right?

2022-05-04 06:29 UTC, amntoppo commented on example/lib/home.dart
> +                      'clientConversationId': '69360869',
This is used in the sample app for testing. It will not affect any customer in anyway.

2022-05-04 06:29 UTC, amntoppo commented on android/src/main/java/io/kommunicate/kommunicate_flutter_plugin/KmMethodHandler.java
> +                            (String) call.argument("teamId"),
Will be adding login check and null check for error handling

2022-05-04 06:29 UTC, amntoppo commented on android/src/main/java/io/kommunicate/kommunicate_flutter_plugin/KmMethodHandler.java
> +                            (String) call.argument("teamId"),
Will be adding login check and null check for error handling

2022-05-04 06:29 UTC, amntoppo commented on ios/Classes/SwiftKommunicateFlutterPlugin.swift
> +                            return
adding trigger error callback

2022-05-04 06:29 UTC, amntoppo commented on ios/Classes/SwiftKommunicateFlutterPlugin.swift
> +                            return
adding trigger error callback

2022-05-04 13:15 UTC, Sathyan-Elangovan commented on android/src/main/java/io/kommunicate/kommunicate_flutter_plugin/KmMethodHandler.java
> +                            (String) call.argument("teamId"),
pending

2022-05-05 05:14 UTC, Sathyan-Elangovan approved these changes

2022-05-10 13:09 UTC, merged